macros:
- macroName: hello-cmd-windows
  executable: cmd.exe
  arguments: "/c echo Hello World"
  description: Echo Hello World message from command prompt
- macroName: ping-google-windows
  executable: cmd.exe
  arguments: "/c ping 8.8.8.8"
  description: Ping google DNS
- macroName: ping-google
  executable: ping
  arguments: 8.8.8.8 -c 4
  description: Ping google MacOs